/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTrackerRouteImport } from './routes/dashboard.tracker'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSalaryRouteImport } from './routes/dashboard.salary'
import { Route as DashboardResumeRouteImport } from './routes/dashboard.resume'
import { Route as DashboardLinkedinRouteImport } from './routes/dashboard.linkedin'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardInterviewRouteImport } from './routes/dashboard.interview'
import { Route as DashboardCoverLetterRouteImport } from './routes/dashboard.cover-letter'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrackerRoute = DashboardTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalaryRoute = DashboardSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinkedinRoute = DashboardLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInterviewRoute = DashboardInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoverLetterRoute = DashboardCoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/cover-letter': typeof DashboardCoverLetterRoute
  '/dashboard/interview': typeof DashboardInterviewRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/linkedin': typeof DashboardLinkedinRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/salary': typeof DashboardSalaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tracker': typeof DashboardTrackerRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/cover-letter': typeof DashboardCoverLetterRoute
  '/dashboard/interview': typeof DashboardInterviewRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/linkedin': typeof DashboardLinkedinRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/salary': typeof DashboardSalaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tracker': typeof DashboardTrackerRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/cover-letter': typeof DashboardCoverLetterRoute
  '/dashboard/interview': typeof DashboardInterviewRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/linkedin': typeof DashboardLinkedinRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/salary': typeof DashboardSalaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tracker': typeof DashboardTrackerRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/applications'
    | '/dashboard/cover-letter'
    | '/dashboard/interview'
    | '/dashboard/jobs'
    | '/dashboard/linkedin'
    | '/dashboard/resume'
    | '/dashboard/salary'
    | '/dashboard/settings'
    | '/dashboard/tracker'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/applications'
    | '/dashboard/cover-letter'
    | '/dashboard/interview'
    | '/dashboard/jobs'
    | '/dashboard/linkedin'
    | '/dashboard/resume'
    | '/dashboard/salary'
    | '/dashboard/settings'
    | '/dashboard/tracker'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/applications'
    | '/dashboard/cover-letter'
    | '/dashboard/interview'
    | '/dashboard/jobs'
    | '/dashboard/linkedin'
    | '/dashboard/resume'
    | '/dashboard/salary'
    | '/dashboard/settings'
    | '/dashboard/tracker'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracker': {
      id: '/dashboard/tracker'
      path: '/tracker'
      fullPath: '/dashboard/tracker'
      preLoaderRoute: typeof DashboardTrackerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/salary': {
      id: '/dashboard/salary'
      path: '/salary'
      fullPath: '/dashboard/salary'
      preLoaderRoute: typeof DashboardSalaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/linkedin': {
      id: '/dashboard/linkedin'
      path: '/linkedin'
      fullPath: '/dashboard/linkedin'
      preLoaderRoute: typeof DashboardLinkedinRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interview': {
      id: '/dashboard/interview'
      path: '/interview'
      fullPath: '/dashboard/interview'
      preLoaderRoute: typeof DashboardInterviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cover-letter': {
      id: '/dashboard/cover-letter'
      path: '/cover-letter'
      fullPath: '/dashboard/cover-letter'
      preLoaderRoute: typeof DashboardCoverLetterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardCoverLetterRoute: typeof DashboardCoverLetterRoute
  DashboardInterviewRoute: typeof DashboardInterviewRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardLinkedinRoute: typeof DashboardLinkedinRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardSalaryRoute: typeof DashboardSalaryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTrackerRoute: typeof DashboardTrackerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardCoverLetterRoute: DashboardCoverLetterRoute,
  DashboardInterviewRoute: DashboardInterviewRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardLinkedinRoute: DashboardLinkedinRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardSalaryRoute: DashboardSalaryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTrackerRoute: DashboardTrackerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
